module.exports = {
  apps: [
    {
      name: "tgbot",
      script: "python3",
      args: "-m bot.main",
      cwd: __dirname,
      interpreter: "none",
      watch: false,
      autorestart: true,
      restart_delay: 3000,
      env: { PYTHONUNBUFFERED: "1" },
    },
    {
      name: "inventory",
      script: "python3",
      args: "-m workers.inventory",
      cwd: __dirname,
      interpreter: "none",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      env: { PYTHONUNBUFFERED: "1" },
    },
    {
      name: "tron_watcher",
      script: "python3",
      args: "-m workers.tron_watcher",
      cwd: __dirname,
      interpreter: "none",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      env: { PYTHONUNBUFFERED: "1" },
    },
    {
      name: "purchaser",
      script: "python3",
      args: "-m workers.purchaser",
      cwd: __dirname,
      interpreter: "none",
      watch: false,
      autorestart: true,
      restart_delay: 3000,
      env: { PYTHONUNBUFFERED: "1" },
    },
  ],
};
